export const ERROR_USER_ALREADY_EXIST = 'ERROR_USER_ALREADY_EXIST';
export const ERROR_INVALID_USERDATA = 'ERROR_INVALID_USERDATA';
export const ERROR_NO_UPLOAD_BUSINESS_LICENSE = 'ERROR_NO_UPLOAD_BUSINESS_LICENSE';