
// Admin Send Mail to User
export const ADMIN_ACTION_SEND_MAIL_CHECK_EMAIL = 'ADMIN_ACTION_SEND_MAIL_CHECK_EMAIL';
export const ADMIN_ACTION_SEND_MAIL_PROXY_PASSWORD = 'ADMIN_ACTION_SEND_MAIL_PROXY_PASSWORD';